dyne/Zenroom

Makefile, build-ios.sh, lib/lua53/src/Makefile, lib/lua53/src/loslib.c, src/Makefile, src/zenroom.c, src/zenroom.h
1. on iOS you can not call to system() syscall so I added a #ifndef to prevent this line to be on the lua code
2. A library cannot have a main(int argc, char **argv) so again I added a #ifndef 
3. The build-ios.sh creates three architectures armv7 (old devices) arm64 (64 bits devices) and x86_64 (simulator) and then creates a fat file with the three combined
=> First attempts to make an ios library with zenroom

Makefile, src/Makefile
I have been using these targets in the makefile to get a shared library in linux, it adds a pedantic way to tag the library ( ARCH VERSION BRANCH and GIT HASH  ) to track zenroom changes, but it is being pointed by a symlin called `libzenroom.so` in our machines.
I would like to know if this is ok to be merge or you think it needs some refinement.
=> linux shared lib targets

Makefile
Also fix non generating the `zenroom.js.mem` on newer emscripten sdk.
For make it work with react-native you also need to provide `crypto.js` file in the same folder and install buffer on the react-native app `npm install buffer`
```
var Buffer = require('buffer/').Buffer
const getRandomValues = (byteArray) => {
for (let i = 0; i < byteArray.length; i++) {
byteArray[i] = Math.floor(256 * Math.random());
}
}
const randomBytes = (size, cb) => {
if (size > 65536) throw new Error('requested too many random bytes')
var rawBytes = new global.Uint8Array(size)
// This will not work in older browsers.
// See https://developer.mozilla.org/en-US/docs/Web/API/window.crypto.getRandomValues
if (size > 0) {  // getRandomValues fails on IE if size == 0
getRandomValues(rawBytes)
}
var bytes = …
```
=> ADD support for react-native

Makefile
We needed to add the math library to compile 🔢 
We only added it for the `musl-system` target, maybe it's needed for other targets as well?
=> [+Jordi] Added ldadd flag for musl-system target

build/zenroom_exec.js
Hereby a small addition in order to make the 'zenroom_exec.js' file immediately runnable by anyone wanting to test this functionality
=> Added implementation of Module.print

.gitignore, Makefile, build/config.mk, build/dl-binaries.sh, build/javascript.mk, build/zip-binaries.sh, src/Makefile
I think it makes more sense naming the javascript-* make rules after the binary format they emit, rather than after the environment for which they were created.
Emscripten by default emits code capable of running in Node, Browser, Shell, Web Worker, and this is also our case, so I replaced `-nodejs` with `-asmjs` (that was particularly misleading as recent Node versions could understand Wasm binaries too) and `-npm` with `-wasm`.
I also added a sample target for a browser-optimized Wasm binary (`emcc -S ENVIRONMENT='web'`) that's named after the output format first, and the specific environment after, so `javascript-wasm-web`, showing differences between output format and target environment.
=> Tidy up javascript build targets

bindings/python3/README.md, bindings/python3/setup.cfg, bindings/python3/setup.py, bindings/python3/zenroom/zenroom.py, bindings/python3/zenroom/zenroom_test.py, docs/website/docs/js/encrypt.js
* Updated with Zenroom 1.0.0
* Removed the Capturer dependency hence resolving the `too many files`
problem
* Slightly improved the error message result parsing with handy methods
* Added return code that now is returned from zen{room,code}_exec calls
* Improved documentation
* Updated references to the new dev.zenroom.org site
* support for Python 3.7.4 and 3.6.9
=> :tada: Preparing 1.0.7rc0 release for python bindings

bindings/java/decode/zenroom/Zenroom.java, bindings/java/testZenroom.java, build/build-java.sh, build/config.mk, build/linux.mk, src/Makefile
@puria as per #https://github.com/DECODEproject/Zenroom/issues/93#issuecomment-613864834 copying existing make patterns from android, this PR adds the Zenroom.java under bindings/java and builds java jni libs with
```
JAVA_HOME=${JAVA_HOME:=`dirname $(dirname $(readlink -f $(which javac)))`} make java-x86_64
```
or
```
build/build-java.sh
```
the jni binders have so far only been tested for x86_64
=> adds native java jni bindings

Makefile
Without this check `make clean` fails in case when milagro makefile hasn't been generated.
=> Check that milagro makefile is generated before running clean target

Makefile, build/config.mk, src/Makefile
The source code and the build code are mixed together. This
will produce some errors during compiling.
This commit adds a build directory for cmake.
To avoid mixing the source code and the build code together.
=> fix: Add build directory for cmake

build/config.mk, src/cortex_m.c, src/zen_random.c
There are some compiling errors when building the cortex-m target.
Such as undefined reference to _sbrk(), _write(), _read()...etc,
use the deprecated API `zenroom_exec_rng_tobuf`, and the wrong brace
position.
This commit link the undefined reference to newlib nano specs, change
the deprecated API to zenroom_exec_tobuf and correct the brace position.
=> fix: Fix errors when building the cortex-m target

.github/workflows/cortex-arm.yml, .gitmodules, src/Makefile, src/cortex_m.c, src/cortex_m.ld, src/zen_io.c
To use the semihosting will let us to test the Zenroom on
qemu-system-arm or such as cortex-m devices more easily.
But for running the semihosting correctly, we need to update the startup
file and the linker scripts.
This commit add a CMSIS repository into submodule for update the startup
file and the linker scripts to CMSIS and update the functions inside
cortex-m.c for semihosting support.
The Zenroom could be test on the following qemu scripts:
```
qemu-system-arm -M mps2-an385 -kernel src/zenroom.bin -semihosting -nographic
```
=> fix: Add semihosting support for Zenroom to run on qemu

src/cortex_m.c, src/zen_io.c
This commit implements the output function for cortex-m target.
Since the QEMU didn't have the stderr and stdout stream. The
cortex-m device need to write the stderr message to semihosting
console via semihosting call. The messages of stdout will be written
into a "stdout" file.
The output will help CI to validate the cortex-m result in QEMU.
=> Implement print stream for cortex-m target

.github/workflows/cortex-arm.yml, build/tests.mk, test/cortex_m_crypto_tests.sh, test/integration_asymmetric_crypto.sh, test/octet-json.sh, test/utils.sh, test/zencode_array/run.sh, test/zencode_credential/run.sh, test/zencode_ecdh/run.sh, test/zencode_hash/run.sh, test/zencode_numbers/run.sh, test/zencode_parser.sh, test/zencode_petition/run.sh
This commit adds the zencode integration test and the crypto
integration test for Arm cortex-m targets.
For testing the Zenroom on the cortex-m3 device, the stderr and stdout
stream should be changed. The stderr messages in Zenroom will be
redirect to semihosting console. The stdout message will be written
into the "stdout" file since the QEMU doesn't have the stderr and stdout
stream.
Since the QEMU also can not receive the stdin stream, the test script
will be written into a temp file. The QEMU will open the temp file
via semihosting to get the test scripts.
=> ci: Improve CI for cortex-m targets

.github/workflows/cortex-arm.yml
The apt upgrade will failed inside ubuntu 20.04 on github actions.
After the image is updated, the apt upgrade can re-enable.
=> ci: Disable apt upgrade

.github/workflows/check-crypto.yml, build/linux.mk
There are several platforms that Zenroom support. Some changes on other specific platform may not easily to check such as cortex m.
This commit adds a github actions CI to check Zenroom will pass on ubuntu, macos and windows platform.
=> ci: Add check-crypto CI for all platform

build/config.mk, build/linux.mk, src/Makefile
The cortex is the build command for building cortex-m target. This
will generate errors when building aarch64 target. This commit
fix the aarch64 build command from arm to aarch64.
=> fix: Add aarch64 support

build/config.mk
This fixes Android builds by removing inherited link libraries (ie -lpthread) in ldflags option.
=> fixes android build linking error

src/lua/crypto_lagrange_interpolation.lua
The new prime is 32bytes long, for this version to work we need
at least 257bits big integer (the sum of two 256bits integer could
be a 257bits integer). Currently we are using 384bits big integer and
they are fine.
=> Fixed prime in lagrange interpolation

bindings/rust/Cargo.toml, bindings/rust/src/lib.rs
Using `String` as function argument, means that the variable will be moved and thus consumed when the function is invoked. This might be good in some cases, where the string passed isn't needed anymore. However, in other cases a new allocation is required to avoid consuming the variable. Since a `CString` (which is just a wrapper over `char*`  is allocated in the bindings anyway, passing `&str` is better way. Also, `&str` is more flexible and thus preferred to `String` as function argument.
This PR also contains an update to the dependencies.
=> Update rust bindings

src/lua/zencode_given.lua
In the given phase DATA and KEYS are always set to nil. Their content is moved in, respectively, IN and KIN, so we need to check the emptiness of the latters.
=> given nothing update

src/lua/zencode_w3c.lua
Looks a bit like sweeping under the carpet, but at least
it is initialized....
=> fix uninitialized ACK data, required by CODEC (fixes #447)

test/bats_setup
SUBDOC was fixed to "lua", and the new SUBDOC defined in the bats files were not taken into account..
=> fix(bats): remove SUBDOC in bats_setup

.github/workflows/main.yml
We are starting to support more and more architectures with planemint and would love to deploy sdist packages so that a smooth deployment with new zenroom packages is garanteed. 
Therefore, I adjusted the pypi deployment workflow to contain sdists.
Signed-off-by: Jürgen Eckel <juergen@riddleandcode.com>
=> added sdist build and deployments for pypi

bindings/rust/src/lib.rs, src/zen_io.c
After changing the body of the test with a loop that executed the test multiple times, something really strange happened.
For a buffer of size 10 * 1024 the for loop executed until the end
For a buffer size of 512 * 1024 or more the number of iteration executed without error is proportional to the size of the buffer.
=> Really weird memory leak

build/config.mk
Using `make win-debug` command, the `debug` overwrite the `clfags` thus the flags
```
-D'ARCH=\"WIN\"' -DARCH_WIN
```
where not used in debug mode
=> build: fix make win-debug command

.github/workflows/publish-binary.yml
adds a release process to github actions, triggered on semantic releases only for linux x86 64bit targets, commandline binary and library (static and shared)
=> feat: build and publish amd64 binaries

src/encoding.c, src/zen_octet.c
There was an undefined behavior when an odd length hex string was converted to octet.
Add check in `hex2buf` and throw a fatal error.
=> fix: 🐛 hex2buf fails when invalid string is passed

.github/workflows/main.yml, bindings/python3/prepare.sh, bindings/python3/setup.py
Reduce the size of the python distribution package from 90 MB to 40 MB.
Tested 🧪 on [matteo-cristino/test_python_release](https://github.com/matteo-cristino/Zenroom/tree/test_python_release) releasing 📦 the package on [test.pypi](https://test.pypi.org/project/personal-zenroom/) (zenroom was already present thus i changed the package name to personal-zenroom).
=> refactor(bindings): ♻️ reduce python binding source distribution

src/lua/zencode_hash.lua, test/zencode/hash.bats
Also deprecated the hash to point of each object in an array with the following message:
```
[W]  DEPRECATED:
create the hash to point '' of each object in ''
use instead
Foreach 'element' in 'array'
When I create the hash to point of 'array'
and I move 'hash to point' in 'array of hashes'
EndForeach
```
=> feat(hash): ✨ zencode statement to create an hash to point

src/lua/crypto_ethereum.lua, test/zencode/ethereum.bats
=> fix(ethereum): 🐛 accept any zenroom type in the store of data

build/tests.mk, test/vectors/check_dilithium.lua, test/vectors/check_kyber.lua, test/vectors/check_sntrup.lua
fixes quantum proof vector tests
=> chore: fix strtok in test

.editorconfig, src/lua/crypto_ethereum.lua, src/lua/zencode.lua, src/lua/zencode_ethereum.lua, test/zencode/ethereum.bats
Now chain id can also be imported from KEYS or DATA.
Chain ID can have encoding 'string' or 'integer'.
When the chain id is set, we look at ACK and see if the
variable references a value which is loaded. In this case:
- if the encoding is 'integer' his numeric value is imported.
- if the encoding is 'string' we try to import its numeric value,
if it fails we import it as `O.from_string` (backward compatibility)
If the name is not loaded from keys or data, we use the value inside
the zencode script
=> fix: 🐛 improve chain id import in ethereum transaction

.github/workflows/main.yml
the debian stretch suite has been moved from deb.debian.org to archive.debian.org (https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html).
=> ci: 👷 fix python build and checks job

src/zen_big.c
A big struct were copied which lead to a shared pointer that could be freed by multiple big_free/big_destroy
=> fix: BIG memory leak on big copy (fix #692)

.editorconfig, bindings/README.md, src/lua/statemachine.lua, src/lua/zencode.lua, src/lua/zencode_debug.lua, src/lua/zencode_dictionary.lua, src/lua/zencode_given.lua, src/lua/zenroom_common.lua, src/zen_parse.c, src/zencode-exec.c, src/zenroom.c, src/zenroom.h, test/zencode/rules.bats, test/zencode/zencode_exec.bats
Extend initialization to accept also an extra input in zencode-exec
Replace C implementation of strtok with Lua one to avoid segfault in statemachine inside protected mode calls (unexplained)
Performance improvements and stability in zencode-exec
=> feat: improve input processing and add extra channel in zencode-exec

.github/workflows/main.yml
This builds are then performed in the release phase, this is added to be sure that after a merging no release build will faill.
After a quick chat with @jaromil we have decided to reduce the meson tests to default gcc and clang present in ubuntu 22.04, that are gcc 11 and clang 14
=> ci(main): 👷 add various os build during tests and reduce meson build to default gcc and clang

src/lua/crypto_bbs.lua, src/lua/crypto_ethereum.lua, src/lua/zencode.lua, src/lua/zencode_ethereum.lua, src/lua/zencode_hash.lua, src/lua/zenroom_common.lua, src/lua/zenroom_hash.lua, src/lua/zenroom_msgpack.lua, test/lua/bbs.lua, test/lua/hkdf.lua
Investigating luacheck warninigs as states in #737 leads to find various pitfalls either in wrong global variable scoping or similar.
This PR will go through most of them eliminating warnings and leading to cleanups where necessary.
=> fix: cleanup and optimization of common lua funcs

bindings/javascript/src/index.spec.ts, bindings/python3/tests/test_all.py, src/lua/init.lua, src/lua/statemachine.lua, src/lua/zencode.lua, src/lua/zencode_debug.lua, src/zenroom.c, test/testgen_sign_verify_tests.sh, test/zencode/bbs_sha.bats, test/zencode/bbs_shake.bats, test/zencode/ecdh.bats, test/zencode/ethereum.bats, test/zencode/generic_bbs.bats, test/zencode/generic_dilithium.bats, test/zencode/generic_ecdh.bats, test/zencode/generic_eddsa.bats, test/zencode/generic_schnorr.bats, test/zencode/given.bats, test/zencode/parser.bats, test/zencode/w3c.bats, test/zencode/zencode_exec.bats
This adds the line number of zencode that aren't recognized and eventually ignored by the parser.
Line number excluded rules and scenario directives.
Tests aren't yet fixed, pending review.
=> feat: print line number of ignored statements

src/lua/zencode.lua, test/zencode/rules.bats
Also remove rule collision ignore since it is not valid anymore
=> fix(zencode): 🐛 deprecate rule caller restroom-mw in favour of rule unknown ignore

src/zen_big.c, src/zen_ecp.c, src/zen_ecp.h, src/zen_ecp2.c, src/zenroom.c, test/bats_zencode
Also make bats tests fails in case of memory left allocated
=> fix: 🐛 free allocated octets in case of errors in new_ecp and new_big

src/lua/zencode_then.lua, test/zencode/then.bats
=> fix(then): 🐛 use deepcopy to copy tables from ACK to OUT

src/lua/zencode_table.lua, src/lua/zencode_when.lua, test/zencode/dictionary.bats, test/zencode/when.bats
=> fix: 🐛 found statements work also with floats 

src/lua/zencode_bbs.lua, src/lua/zencode_bitcoin.lua, src/lua/zencode_credential.lua, src/lua/zencode_ecdh.lua, src/lua/zencode_eddsa.lua, src/lua/zencode_ethereum.lua, src/lua/zencode_given.lua, src/lua/zencode_hash.lua, src/lua/zencode_petition.lua, src/lua/zencode_pvss.lua, src/lua/zencode_qp.lua, src/lua/zencode_reflow.lua, src/lua/zencode_schnorr.lua, src/lua/zencode_then.lua, src/lua/zencode_verify.lua
This PR changes the Zencode definition lua code to insure that all statements (`Given(...) When(...) Then(...) IfWhen(...)`) are made on the same line, so that any editor or `grep` or `awk` or emacs `occur` function can easily list all statements declared in a Lua source file.
=> inline statements in credentials

src/lua/zencode_given.lua, src/lua/zencode_reflow.lua, test/zencode/array.bats, test/zencode/branching.bats, test/zencode/given.bats, test/zencode/reflow.bats
This will help to ensure that the zentype declared in the codec is the right one and that the statements which act differently based on the zentype works as intended.
=> fix(given): 🐛 add data type validation during giving phase

docs/pages/apiroom.md
removed the -d parameter from the Docker launch instruction, cause better suitable for testing, in the Apiroom docs
=> docs: update Docker docs of apiroom.md

src/lua/zencode_given.lua, test/zencode/given.bats
This is needed when the prefix or suffix contains a withspace, since the inline value will replace it with an underscore
=> fix(given): 🐛 prefix and suffix can be passed as input varibale

src/lua/zencode_time.lua, test/zencode/time.bats
since ther are no operations on timestamps, then we need to cast it to confront it with other timestamps or to perform any mathematic formula over them
=> feat(time): ✨ statement to cast timestamp into integer

src/lua/zencode.lua, test/zencode/logfmt.bats
The newline was breaking json logfmt
=> fix(zencode): 🐛 remove newline in error thrown from invalid transition

bindings/javascript/src/index.ts
This console.log generate a lot of messages when using ncr that makes it harder to understand if real errors happen
=> fix(javascript): remove console.log from introspect function

bindings/javascript/src/index.spec.ts, bindings/javascript/src/index.ts, build/config.mk, src/lua/init.lua, src/lua/zencode.lua, src/zenroom.c, src/zenroom.h
- feat: add strict_parse configuration flag
- fix: return of parse is json encoded
- fix: parser does not ignore invalid statement that are not at the contract borders
- feat(zenroom): ✨ add new C api to parse zencode contracts
- feat(javascript): ✨ expose zencode_parse_contract api to js
- refactor: ♻️  add parse api input to decide whether it has to be strict or not
- feat(javscirpt): ✨ parse api is by default strict, add also safe_zencode_parse_contract as an alias for non strict parsing
=> feat: ✨ add zencode contract parse api

src/lua/zencode_data.lua, test/zencode/then.bats, test/zencode/zencode_exec.bats
- fix: print all empty octets as empty strings
- test(zencode): add failing tests with empty octets in the trace
=> fix: print all empty octets as empty strings

bindings/javascript/src/index.spec.ts, src/zenroom.c
- fix(zenroom): initialize zenroom before script check, in this way the error on empty script follows the logfmt specification
- test(js): update error returned by empty script
=> fix(zenroom): initialize zenroom before script check, in this way the error on empty script follows the logfmt specification

src/lua/zencode_ecdh.lua, src/zen_ecdh.c
- fix(zen_ecdh): check secret key size on generation of the public one
- chore(zencode_ecdh): avoid code duplication
=> fix(zen_ecdh): check secret key size on generation of the public one

Dockerfile
We add readline-dev to Dockerfile
RUN apk add --no-cache zsh linux-headers build-base cmake readline-dev
An error occurred while compiling the image:
**cannot find -lreadline: No such file or directory**
`In file included from zencode-exec.c:30:
/usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
1 | #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
|  ^~~~~~~
gcc -O2 -fstack-protector-all -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fPIE -fPIC -I. -I../lib/lua54/src -I../lib/milagro-crypto-c/build/include -I../lib/milagro-crypto-c/include -I../lib/ed25519-donna -I../lib/mimalloc/include -Wall -Wextra zenroom.o zen_error.o lua_functions.o lua_modules.o lualibs_detected.o lua_shims.o encoding.o base58.o rmd160.o …
=> Add readline-dev

README.md
Changes in ReadMe file about Dependencies from xxd
I use docker image FROM python:3.9
in order to install the package via github, because I think to add additional code to one lua file of the project and so that the changes are available via Python 3.8+ module zenroom
=> For docker image FROM python:3.9 need xxd also

.github/workflows/publish-docker.yml
=> ci: update docker release

src/lua/zencode_http.lua, test/zencode/http.bats
- fix(http): improve uri parsing
- fix(http): allow to append also numbers as url query parameters
=> fix(http): allow generic schema and to append numbers as query parameters

src/lua/zencode_http.lua, test/zencode/http.bats
- fix(http): separate hostname and port before host checks
- test(http): parse url with port
=> fix(http): separate hostname and port before host checks

docs/pages/zenroom-config.md, src/lua/init.lua, src/lua/zencode.lua, src/lua/zencode_foreach.lua, src/lua/zencode_given.lua, src/zen_config.c, src/zenroom.c, src/zenroom.h
Refactor also a bit the ITER stack
=> feat: improve general performance by reducing the total numbers of call to garbage collector

README.md
add also CC0 to list of used license from external libraries
=> docs(README): update reuse link from non existing github action to reuse compliance page

src/lua/zencode_when.lua, test/zencode/numbers.bats
first minus sign in paranthesis was always considered as unary minus also in case like (a-b) leading to errors
=> fix: minus sign in parathesis

.github/workflows/main.yml, src/lua/init.lua, src/lua/semver.lua
This reproduces @andrea-dintino error trying to build zenroom on arm32 with `make -f build/linux.mk` command
=> ci: add arm32 build test

src/lua/zencode_array.lua, src/lua/zencode_when.lua, test/zencode/array.bats, test/zencode/cookbook_when.bats, test/zencode/when.bats
deprecate "create copy of element '' from array ''" in favour of the latter
=> feat: add support for array and key as a variable in "copy/move from to" statement

src/lua/zencode_debug.lua, src/lua/zencode_when.lua
- fix: use debug encoding on debug heap dump
- fix: in "copy to" statement check for source existance
=> fix: use debug encoding on debug heap dump

src/lua/zencode_hash.lua, src/lua/zenroom_hash.lua, test/zencode/rules.bats
- **refactor(zenroom_hash): improve code readibility in hash initialization**
- **refactor(zenroom_hash): if present use already initialize hash everywhere**
- **refactor: more readable and easy to extend code for hashing statements**
=> refactor(hash): improve code readability, try to avoid multiple hash initialization and expose also shake256 in zencode hash statement

build/meson.build, src/lua/zencode_table.lua, test/zencode/table.bats
More testing is needed before merging
=> feat(table): ✨ first implementation of pointer system in zencode

docs/pages/zencode-scenarios-ethereum.md
I added to the documentation a way to create and verify contract 1155 in python. And also a mint token with various calls to the balanceOF function.
This script also contains examples for a clear understanding of the need for a digital signature for each new token mint.
Hopefully this information can be useful if there is ever a need to add the same mechanisms ERC1155 to Zencode.
Because while Ethereum is very popular right now, Ethereum's Keccak-256 Algorithm is currently obsolete due to the overhead of maintaining zero-information proofs. So there is a chance that Ethereum will fork and the current implementations will be forgotten.
Geth installed on most private Ethereum blockchains is already obsolete.
We add option "evmVersion": "paris" for support stable version of geth Ethereum …
=> Dosc Erc1155 info

.mise.toml, bindings/javascript/src/index.spec.ts, bindings/javascript/src/index.ts
- **chore: add yarn to mise tools list**
- **feat(js): add decode_error api**
=> feat(js): add decode_error api

docs/pages/zencode-cookbook-when.md, src/lua/zencode_given.lua, src/lua/zencode_hash.lua, src/lua/zenroom_common.lua, src/lua/zenroom_hash.lua, test/zencode/hash.bats
=> Initial implementation of multibase encoding

test/vectors/check_w3c-vc-di-eddsa.lua, test/vectors/eddsa.bats
The following test vector for EdDSA have been implemented from [w3c specification](https://www.w3.org/TR/vc-di-eddsa/):
- B.1 Representation: eddsa-rdfc-2022
- B.2 Enhanced Example for Representation: eddsa-rdfc-2022
- B.3 Representation: eddsa-jcs-2022
- B.4 Representation: Ed25519Signature2020
=> test(ed): new test vectors from w3c-vc-di-eddsa

build/android.mk
attempt to fix "cannot locate symbol "__android_log_print""
=> fix: add -llog to android .so build

build/android.mk
Attempt to fix: 
Process: com.example.zencode, PID: 11293
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "log2" referenced by "/data/app/~~LIsElfhvdxiIBmiDZeFmCw==/com.example.zencode-6UJi7EjxckO2sS-T1fg0NA==/lib/x86_64/libzenroom.so"
=> fix: add -lm in android.mk

src/zen_big.c, test/lua/big_gregorian_epoch_timestamp.lua, test/lua/primitives.bats
- **fix: normalize big import when using BIG.new with numbers**
- **fix(zen_big): BIG.new detect when number grater than 32 bits are imported and throw an error and handle also string inputs**
=> fix: normalize big import when using BIG.new with numbers and handle better big numbers and strings in input

src/lua/zencode_jws.lua
this is needed when scenario 'jws' is used
=> fix(zencode_jws): require crypto_jose
