dyne/Zenroom

README.md

I noticed that my first name was spelled incorrectly. This PR proposes to correct it.

readme: Fix a typo

---

.travis.yml
Makefile
README.md
docs/config.zsh
extras/shell_minimal.html
src/Makefile
test/test_luazen.lua
test/zenroom_exec.js

more builds and tests on travis, including js
(emscripten used from docker)

Travis artifacts2

---

test/ecp_elgamal.lua

Added some Zero Knowledge Proof to elgamal.lua
- Verifies that the initial state is 0
- Verifies that the users only adds 0 or 1

ElGamal with ZKP

---

examples/zencode_coconut/run_coconut_example.sh

Add references to Coconut .pdf ( https://arxiv.org/pdf/1802.07344.pdf ) and to variable names, used in the paper

Added reference to Coconut paper

---

build/javascript.mk

Fix for #55

---

.travis.yml

Improve travis file

---

src/zen_ecdh.c
src/zen_ecdh.h
src/zen_ecdh_factory.c
test/ecdh.lua

This is still WIP. 
There are some interesting findings:
* Tests fails if an empty or NULL string is passed.
* The public key is defined as the double of its value. If corrected, the tests fail.
I will continue checking this ;)

Start checking some ecdh implementation

---

src/zen_ecdh.c
test/ecdh.lua

This checks:
* The length of some params (the iv and tag)
* Add references to RFCs.

Solve TODOs

---

bindings/javascript/README.md
docs/pages/javascript.md
docs/pages/zenroom-javascript1.md
docs/pages/zenroom-javascript2.md
docs/pages/zenroom-javascript3.md

Docs dev - fixed documentation

---

docs/pages/zenroom-javascript1.md
docs/pages/zenroom-javascript2.md
docs/pages/zenroom-javascript3.md

Few fixes i had to do to follow the JS related documentation without errors (and fewer warnings)

update zen docs related JS

---

test/lagrange.lua

added lagrange.lua test

---

lib/lua53/src/lapi.c
lib/lua53/src/lauxlib.c
lib/lua53/src/lcode.c
lib/lua53/src/ldebug.c
lib/lua53/src/llex.c
lib/lua53/src/lparser.c
lib/lua53/src/lua.h
lib/lua53/src/luac.c
lib/lua53/src/lundump.c

Cherrypick of fixes in Lua 5.3.6 which is also the last in 5.3 series

update to relevant changes in Lua 5.3.6

---

src/lua/crypto_schnorr_signature.lua
test/schnorr.lua

Abbettowski

---

Makefile
build/config.mk

Tiny fix removing hardcoded path to "ar" executable

Remove hardcoded ar path

---

build/tests.mk
lib/lua53/src/ldo.c
src/cortex_m.c
test/zencode_cookbook/run-all.sh
test/zencode_cookbook/run-dictionaries.sh
test/zencode_cookbook/run-given.sh
test/zencode_cookbook/run-hash-pdf.sh
test/zencode_cookbook/run-intro.sh
test/zencode_cookbook/run-scenarios-ecdh-encrypt-json.sh
test/zencode_cookbook/run-scenarios-ecdh.sh
test/zencode_cookbook/run-then.sh
test/zencode_cookbook/run-when.sh

This commit add the more check of test script for qemu cortex-m device.

ci: Improve test script

---

docs/pages/cortex.md

After updated the qemu command for cortexm unit-test. The docs
should also be updated.

docs: Update qemu command for cortexm

---

bindings/python3/zenroom/_config.py

From @sbocconi fix
[https://github.com/dyne/Zenroom/issues/203#issuecomment-861791844](https://github.com/dyne/Zenroom/issues/203#issuecomment-861791844)

fixed loading of zenroom.so in python

---

src/lua/zencode.lua
src/lua_functions.c
src/zenroom.c
test/zencode_branching/run.sh

Branch fix

---

src/lua/crypto_credential.lua
src/lua/zencode_credential.lua

safer when using smaller curves like 381
maybe this can be a solution for #214

compute modulo curve order on all INT.new

---

.github/workflows/reuse.yml
.gitignore
.reuse/dep5
.travis.yml
Agreement.md
ChangeLog.md
LICENSES/AGPL-3.0-or-later.txt
LICENSES/Apache-2.0.txt
LICENSES/MIT.txt
Makefile
README.md
TODO.md
package.json.license

ci: 👷  REUSE compliancy

---

Makefile
build/tests.mk
src/Makefile
src/encoding.c
src/encoding.h

removed some ARCH defines compile time
using char in place of uint8_t in encoding source
fix source object files in makefile

various build fixes

---

.github/workflows/python.yml

- ci(python): 👷  Linux problem on workflow
- Disable musllinux

python test fix

---

src/lua/crypto_schnorr_signature.lua
src/lua/zencode_keys.lua
src/lua/zencode_schnorr.lua
test/schnorr.lua
test/zencode_schnorr/run.sh

I apologize again for the mess in the previous PR. 
This replace the previous one with the same changes (except for the commits involving ecdh signature, i will do it in a separate PR).

Schnorr singature

---

src/lua/zencode_array.lua
test/zencode_array/run.sh

New Zencode statement to flat an array

Zencode: create flat array

---

src/lua/zencode_data.lua
test/zencode_ethereum/run.sh

fix: encoding on print

---

bindings/javascript/src/index.spec.ts
src/bip39_english.h
src/cli.c
src/cortex_m.c
src/lua_functions.c
src/lua_modules.c
src/lua_shims.c
src/zen_big.c
src/zen_config.c
src/zen_ecdh.c
src/zen_error.c
src/zen_error.h
src/zen_io.c
src/zen_octet.c
src/zen_random.c
src/zenroom.c
src/zenroom.h

Includes a refactoring of the messaging system

Make Zenroom reentrant

---

src/lua/crypto_schnorr_signature.lua
src/lua/zencode_schnorr.lua
test/zencode_schnorr/run.sh

fix(schnorr): loaded key is now taken modulo the order of the curve

---

src/lua/zencode.lua
test/zencode_branching/run.sh

fix(then): 'print the' in branching

---

test/bats_zencode

fix(bats): If zencode test is successful then the script is saved in SUBDOC 

---

build/config.mk
lib/lua53/src/luaconf.h
lib/pqclean/fips202.c
lib/pqclean/sha2.c
src/api_hash.c
src/cli.c
src/randombytes.c
src/repl.c
src/zen_big.c
src/zen_hash.c
src/zen_memory.c
src/zen_memory.h
src/zen_octet.c
src/zen_parse.c
src/zenroom.c
src/zenroom.h

now can deactivate mimalloc at build time for some targets
removed leftover wrapper for memory allocation in headers

build and header cleanup for new memory allocation

---

.github/workflows/meson.yml
Makefile
build/config.mk
build/javascript.mk
build/linux.mk
build/meson.mk

speed up C building time by adopting ccache - also for meson targets in github actions

Ccache builds

---

build/codegen_ecdh_factory.sh
src/zen_big.c
src/zen_big.h
src/zen_config.c
src/zen_ecdh.c
src/zen_ecp.c
src/zen_ecp2.c
src/zenroom.c

added lua_State in scope of generated ecdh factory code

Cleanup log messages and validate configuration string

---

bindings/javascript/src/index.spec.ts
src/zenroom.c

fix js to include teardown messages

---

build/config.mk

move up ldadds in config.mk to make filter-out mimalloc effective

fix libc malloc builds

---

src/lua/zencode_dictionary.lua
test/zencode/dictionary.bats

fix(dictionary): 🐛 codec of picked up object

---

src/lua/zencode_when.lua
test/zencode/when.bats

this allows to encode values inside a When block and append them to others

feat: append an string encoding to a another string

---

src/lua/zencode_dictionary.lua
test/zencode/dictionary.bats
test/zencode/foreach.bats

fix(dictionary): 🐛 move from and copy in dictionaries/arrays statements

---

src/lua/zencode_then.lua
test/zencode/then.bats

fix(then): 🖨️ print data from

---

src/lua/zencode_keyring.lua
src/lua/zencode_when.lua
test/zencode/when.bats

add copy and move inside tables and create a string encoding of objects

feat: improve various operations on strings

---

src/lua/zencode_w3c.lua
test/zencode/w3c.bats

feat(w3c): ✨ extract pubkeys from verification method

---

docs/pages/zencode-cookbook-given.md
docs/pages/zencode-cookbook-when.md
docs/pages/zencode-list.md
docs/pages/zencode-rules.md
src/lua/zencode_data.lua

fix(cbor): remove CBOR from docs and rules

---

.github/workflows/main.yml
build/meson.build
build/release-intro.md
src/Makefile
src/cli.c
src/zenroom.c

may use this PR to add more necessary build information inside the Zenroom runtime

fix: hard-code build year at build time

---

bindings/ios/README.md
bindings/ios/Zenroom.h
bindings/ios/Zenroom.m

fix(ios): add iOS bindings and notes

---

src/lua/crypto_bbs.lua
src/lua/zencode_bbs.lua

making sure we don't lose track of these notes

include issue #645 in source comments

---

src/lua/zencode_data.lua
src/lua/zencode_ecdh.lua
src/lua/zencode_ethereum.lua
src/lua/zencode_qp.lua
src/lua/zencode_schnorr.lua
src/lua/zencode_then.lua
src/lua/zencode_w3c.lua
test/zencode/ethereum.bats

fix: 🐛 print tables of schemas

---

.gitignore
src/cli-zenroom.c

fix(cli-zenroom): 🐛 add foreach statements in zencode introspection

---

src/lua/.luacheckrc
src/lua/inspect.lua
src/lua/zencode.lua
src/lua/zencode_data.lua

enhance compatibility with Lua 5.1 base standard

fix: remove all goto from lua code

---

docs/index.html
package.json

fixed [Object Promise] issue in docs following
https://stackoverflow.com/questions/76530311/mermaid-in-docsify-return-object-promise

fix mermaid issue in docs

---

bindings/javascript/package.json
build/embed-lualibs

this is optimizing the performance of javascript builds of zenroom

feat: enable bytecode compilation of lua in js build

---

src/lua/crypto_ethereum.lua
src/lua/zencode_ethereum.lua
test/zencode/ethereum.bats

feat(ethereum): ✨ recover address from message and signature

---

Makefile
build/meson.build
build/meson.mk
test/benchmark/all_tests/bench.sh

In order to try this, before this PR is merged you have to change line 16 in test/benchmark/all_tests/bench.sh from
```
make meson-benchmark
```
to 
```
make meson-test
```
since Zenroom master branch has not yet the meson-benchmark target.

test: 🧪 add benchmark

---

src/lua/crypto_bbs.lua
src/lua/zencode_bbs.lua
test/zencode/bbs_sha.bats

fix(bbs): 🐛 check that message signed by bbs is an element or an array of elements

---

bindings/javascript/README.md
docs/pages/javascript.md
docs/pages/zenroom-javascript2b.md
docs/pages/zenroom-javascript3.md

Remove references mentioning installation of zenroom@next npm

docs: remove zenroom@next references

---

build/meson.build
src/lua/crypto_transcend.lua
src/lua/init.lua
src/lua/zencode.lua
src/lua/zencode_data.lua
src/lua/zencode_debug.lua
src/lua/zencode_keyring.lua
src/lua/zencode_transcend.lua
src/zen_aes.c
src/zen_octet.c
test/lua/crypto.bats
test/lua/transcend.lua
test/zencode/transcend.bats
test/zencode/zencode_exec.bats

New crypto protocol for stealth communication

TRANSCEND crypto protocol

---

src/zen_time.c
test/zencode/time.bats

fix(time): 🐛 add check that time imported from string are in integer range

---

docs/pages/zencode-scenarios-ethereum.md

docs: fix typos

---

docs/doc_needed/run.sh
docs/examples/zenroom-bot.py

chore: fix typos

---

bindings/javascript/package.json

chore: correct SPDX identifier in package.json
fixes #851

fix: remove yarn as a dep in js bindings

---

.github/workflows/main.yml

chore: remove old EOL lang versions

---

.github/workflows/main.yml
build/config.mk
build/meson.build
src/cli-zenroom.c
src/cortex_m.c
src/repl.c
src/zencode-exec.c
src/zenroom.c
src/zenroom.h

Some improvements to the old zenroom cli tool including readline and sideloading

Command-line tool enhancements

---

src/zen_big.c
src/zen_ecdh.c
src/zen_octet.c
test/lua/big_decimal.lua

TODO: add tests and look in the code for other places where lua_tointegerx is used and tests also that parts
fix #857

fix: octet from number

---

build/config.mk
test/lua/native/sort.lua

fix: exclude javascript tests that use too much memory

---

.github/workflows/main.yml

bump also node to version 20 in semantic release and npm release jobs

ci: 👷 bump actions to latest versions

---

docs/examples/zencode_cookbook/mldsa44/alice_keygen.zen
docs/examples/zencode_cookbook/mldsa44/alice_pubkey.zen
docs/pages/zencode-scenarios-qp.md
test/zencode/generic_mldsa44.bats

- test(zencode): fix conflicting name in mldsa44 test
- docs(qp): update file name for mldsa44 examples

docs(qp): fix mldsa44 examples

---

.github/workflows/main.yml
build/apple-ios.mk

fix CI to restore linux tests and run meson tests

---

.github/workflows/main.yml
bindings/javascript/package.json
bindings/javascript/yarn.lock

- chore: remove yarn from javascript dependencies
- ci(js): remove cwd since working directory is already set to the right folder

chore: remove yarn from javascript dependencies

---

src/lua/zencode_sd_jwt.lua
test/zencode/sd_jwt.bats

as stated by https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-13.html#name-credential-issuer-metadata-p

fix(sd_jwt): credential_configuration_supported is a dictionary where the key is the unique identifier

---

bindings/javascript/README.md
docs/pages/javascript.md
docs/pages/zenroom-javascript-react-with-next.md
docs/pages/zenroom-javascript1b.md
docs/pages/zenroom-javascript2b.md
docs/pages/zenroom-javascript3.md

- docs: update some js documentation
- docs: fix react documentation

docs: update js documentation and fix react example

---

docs/_media/run_utterances.sh
docs/_media/zencode_utterances_reworked.yaml
docs/pages/zencode-list.md
src/lua/zencode_ethereum.lua

- docs: update script to generate list of zenroom statements
- docs: update list of statements, add missing scenarios and add if and foreach sections
- refactor(ethereum): remove the possibility to use a statement as an if since it has no zencode_assert in it

docs: update list of all zencode statements

---

src/zen_rsa.c

fix also some small indendation issues

chore(zen_rsa): always initialize all the octets at the beginning of the functions

---

Dockerfile
lib/pqclean/ml-dsa-44/poly.c
lib/pqclean/ml-dsa-44/symmetric.h
lib/pqclean/ml-kem-512/indcpa.c
lib/pqclean/ml-kem-512/symmetric-shake.c
lib/pqclean/ml-kem-512/symmetric.h
src/api_sign.c

- fix(lib/pqclean): update the use of incremental and non-incremental apis
- fix(sign_api): incompatible types
- fix(Dockerfile): copy files from local folder

fix: build on alpine image

---

Makefile

- fix(Makefile): update locations of zenroom and zencode-exec executable on clean target
- chore: remove empty file

fix(Makefile): update clean target

---

src/lua/zencode_keyring.lua

refactor also file format that now is divided in import/export, zencode_statements and global utilities (a bit easier to navigate)

refactor(keyring): replace if statements with table lookup

---

src/lua/crypto_w3c.lua
src/lua/zencode_es256.lua
src/p256-m.c
src/p256-m.h
src/zen_p256.c
test/zencode/sd_jwt.bats
test/zencode/w3c.bats

Add also some p256 primitives as:
* public key to x, y
* public key to compressed form
* public key validation

feat(p256): support all form of public keys (raw, compressed and uncompressed)

---

src/lua/crypto_bbs.lua
src/lua/zencode_bbs.lua
test/lua/bbs.lua
test/lua/bbs_zkp.lua

fix: check pk in crypto sign

---

lib/milagro-crypto-c/benchmark/CMakeLists.txt
lib/milagro-crypto-c/cmake/AMCLExpand.cmake
lib/milagro-crypto-c/cmake/AMCLParameters.cmake
lib/milagro-crypto-c/cmake/PythonSiteDirs.cmake
lib/milagro-crypto-c/cmake/SetOSVariable.cmake
lib/milagro-crypto-c/examples/CMakeLists.txt
lib/milagro-crypto-c/python/CMakeLists.txt
lib/milagro-crypto-c/test/CMakeLists.txt
src/lua/zencode_when.lua

this table was moved to the intern function

chore: remove unused table in zero removes

---

src/lua/zencode_given.lua
test/zencode/float.bats
test/zencode/given.bats

new given statement to get a value from a portion of an object inside a path

feat: given part of path after prefix

---

src/lua/zencode_es256.lua

This PR will remove the hard-coded setting of ES256 signature from SD-JWT and enable it to use any signature available in Zenroom, it will also improve ES256 when possible and a few things in default serialization.

Refactor the SD-JWT implementation to support more signature types

---

.github/workflows/main.yml
.mise.toml
bindings/javascript/package.json
bindings/javascript/yarn.lock

test js on lts/* and current and release using node 22

ci(js): move to node 22

---

src/lua/zencode_data.lua
src/lua/zencode_time.lua
test/zencode/time.bats

this can be helpfull for date in w3c vc or did

feat(time): add utc encoding

---

bindings/samples/node/.gitignore
bindings/samples/node/README.md
bindings/samples/node/index.js
bindings/samples/node/package-lock.json
bindings/samples/node/package.json

Adds a sample project to test the zenroom.js build.

feat: add nodejs sample project

---

.github/workflows/main.yml
build/musl.mk
build/posix.mk
lib/longfellow-zk/algebra/limb.h

- build(musl): add longfellow-zk and zstd as deps
- fix: define limb_t based on architecture for consistent typedef

fix: musl build
